<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FinanceTracker.Domain\FinanceTracker.Domain.csproj" />
    <ProjectReference Include="..\FinanceTracker.Infra\FinanceTracker.Infra.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <Name>FinanceTracker.Application</Name>
    <RootNamespace>FinanceTracker.Application</RootNamespace>
    <AssemblyName>FinanceTracker.Application</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
